<?php

   // use Drupal\Core\Language\LanguageInterface;
   use Drupal\views\Plugin\views\cache\CachePluginBase;
   use Drupal\views\Plugin\views\PluginBase;
   use Drupal\views\ViewExecutable;
   use Drupal\views\Plugin\views\query\QueryPluginBase;


  function viewmodule_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();


    if ($view->id() == 'role_based_view')
    {
      $query->addWhere(1,'node__field_type_of_user.field_type_of_user_target_id',1,'=');
    }
}
